module.exports = {
  purge: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  darkMode: false, // or 'media' or 'class'
  theme: {
    colors: {
      black: "#2B3140",
      gray: "#D1D7E5",
      "black-700": "#4F586E",
      "black-500": "#6E7A96",
      "black-300": "#99A2B8",
      "black-100": "#D1D7E5",
      "black-50": "#EDEEF8",
      bug: "#5BC468",
      dragon: "#FF5775",
      fairy: "#F19AB5",
      fire: "#EF8148",
      ghost: "#7E67F6",
      ground: "#B94D2A",
      normal: "#C5CCDC",
      psychic: "#F5629D",
      steel: "#8698C6",
      dark: "#687289",
      electric: "#F6C94F",
      fighting: "#E3524A",
      flying: "#599BD9",
      grass: "#3F8A84",
      ice: "#78B6FF",
      poison: "#A87EF7",
      rock: "#A3A3AB",
      water: "#77D4F5",
      white: "#FFFFFF",
      primary: "#3156C6",
      success: "#1CBB30",
      danger: "#E3190E",
      lightgrey: "#D1D7E5",
      lightblue: "#EDEEF8",
      shade: "#99A2B8",
    },
    extend: {
      boxShadow: {
        shadow: "0 0 30px rgba(0, 0, 0, 0.1)",
      },
      fontSize: {
        heading: "24px",
        "body-01": "16px",
        "body-02": "14px",
        "body-03": "12px",
        subtitle: "10px",
      },
      fontFamily: { nunito: "Nunito" },
      height: {
        filtercircle: "15px",
        card: "204px",
        avatar: "104px",
        add: "14px",
        fav: "18.35px",
        topbar: "172px",
        downbar: "32px",
        navbarmodal: "72px",
      },
      width: {
        filtercircle: "15px",
        card: "148px",
        dropbox: "40px",
        "modal-sm": "560px",
      },
      lineHeight: {
        subtitle: "12px",
      },

      maxWidth: {
        fullscreen: "1440px",
        searchbar: "432px",
        navbarmodal: "645px",
      },

      maxHeight: {
        pokemoncontainer: "692px",
        form: "592px",
        "50p": "50%",
      },

      backgroundImage: (theme) => ({
        search: "url('./img/search.svg')",
        expand: "url('./img/expand.svg')",
        pokedex: "url('./img/pokedex.svg')",
        teams: "url('./img/teams.svg')",
        favorites: "url('./img/favpage.svg')",
        signin: "url('./img/signin.svg')",
      }),
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
